const attributes = [
    {
        name: "Штрихкод",
        code: "barcode",
        type: "text",
        required: true,
        validation: { regex: /^[\d\s;]+$/, // Allows digits, semicolons, and spaces
            errorMessage: "Только цифры и ;" 
        },
        defaultValue: "",
        width: "280px",
    },
    {
        name: "Название товара",
        code: "longName",
        type: "text",
        required: false,
        validation: { maxLength: 100 },
        defaultValue: "",
        width: "600px",
    },
    {
        name: "Кол-во",
        code: "markCount",
        type: "number",
        required: true,
        validation: { min: 1, max: 999 },
        defaultValue: "",
        width: "60px",
    },
    {
        name: "Юнит",
        code: "markCountUnitList",
        type: "select",
        required: true,
        values: [
            { name: "мл", code: "millilitre", aliases: ["миллилитры", "ml"] },
            { name: "л", code: "liter", aliases: ["литры", "l"] },
            { name: "г", code: "gram", aliases: ["граммы", "g"] },
            { name: "кг", code: "kilogram", aliases: ["килограммы", "kg"] },
            { name: "шт.", code: "unit", aliases: ["штуки", "pcs"] },
        ],
        defaultValue: "",
        width: "60px",
    },
    {
        name: "Страна",
        code: "countryISO",
        type: "select",
        required: false,
        values: [
        
{ name: "Аруба", code: "ABW", aliases: ["Aruba"] },
{ name: "Афганистан", code: "AFG", aliases: [] },
{ name: "Ангола", code: "AGO", aliases: [] },
{ name: "Ангилья", code: "AIA", aliases: [] },
{ name: "Аландские острова", code: "ALA", aliases: [] },
{ name: "Албания", code: "ALB", aliases: [] },
{ name: "Андорра", code: "AND", aliases: [] },
{ name: "Объединённые Арабские Эмираты", code: "ARE", aliases: ["ОАЭ"] },
{ name: "Аргентина", code: "ARG", aliases: [] },
{ name: "Армения", code: "ARM", aliases: [] },
{ name: "Американское Самоа", code: "ASM", aliases: [] },
{ name: "Антарктика", code: "ATA", aliases: [] },
{ name: "Французские Южные и Антарктические территории", code: "ATF", aliases: [] },
{ name: "Антигуа и Барбуда", code: "ATG", aliases: [] },
{ name: "Австралия", code: "AUS", aliases: [] },
{ name: "Австрия", code: "AUT", aliases: [] },
{ name: "Азербайджан", code: "AZE", aliases: [] },
{ name: "Бурунди", code: "BDI", aliases: [] },
{ name: "Бельгия", code: "BEL", aliases: [] },
{ name: "Бенин", code: "BEN", aliases: [] },
{ name: "Бонайре", code: "BES", aliases: [] },
{ name: "Буркина-Фасо", code: "BFA", aliases: [] },
{ name: "Бангладеш", code: "BGD", aliases: [] },
{ name: "Болгария", code: "BGR", aliases: [] },
{ name: "Бахрейн", code: "BHR", aliases: [] },
{ name: "Багамские острова", code: "BHS", aliases: [] },
{ name: "Босния и Герцеговина", code: "BIH", aliases: ["Босния"] },
{ name: "Сен-Бартелеми", code: "BLM", aliases: [] },
{ name: "Беларусь", code: "BLR", aliases: ["Белоруссия"] },
{ name: "Белиз", code: "BLZ", aliases: [] },
{ name: "Бермудские Острова", code: "BMU", aliases: [] },
{ name: "Боливия", code: "BOL", aliases: [] },
{ name: "Бразилия", code: "BRA", aliases: [] },
{ name: "Барбадос", code: "BRB", aliases: [] },
{ name: "Бруней", code: "BRN", aliases: [] },
{ name: "Бутан", code: "BTN", aliases: [] },
{ name: "Остров Буве", code: "BVT", aliases: [] },
{ name: "Ботсвана", code: "BWA", aliases: [] },
{ name: "Центральноафриканская Республика", code: "CAF", aliases: [] },
{ name: "Канада", code: "CAN", aliases: [] },
{ name: "Кокосовые острова", code: "CCK", aliases: [] },
{ name: "Швейцария", code: "CHE", aliases: [] },
{ name: "Чили", code: "CHL", aliases: [] },
{ name: "Китай", code: "CHN", aliases: [] },
{ name: "Кот-д’Ивуар", code: "CIV", aliases: [] },
{ name: "Камерун", code: "CMR", aliases: [] },
{ name: "Демократическая Республика Конго", code: "COD", aliases: [] },
{ name: "Конго", code: "COG", aliases: [] },
{ name: "Острова Кука", code: "COK", aliases: [] },
{ name: "Колумбия", code: "COL", aliases: [] },
{ name: "Коморы", code: "COM", aliases: [] },
{ name: "Кабо-Верде", code: "CPV", aliases: [] },
{ name: "Коста-Рика", code: "CRI", aliases: [] },
{ name: "Куба", code: "CUB", aliases: [] },
{ name: "Кюрасао", code: "CUW", aliases: [] },
{ name: "Остров Рождества", code: "CXR", aliases: [] },
{ name: "Острова Кайман", code: "CYM", aliases: [] },
{ name: "Кипр", code: "CYP", aliases: [] },
{ name: "Чехия", code: "CZE", aliases: [] },
{ name: "Германия", code: "DEU", aliases: [] },
{ name: "Джибути", code: "DJI", aliases: [] },
{ name: "Доминика", code: "DMA", aliases: [] },
{ name: "Дания", code: "DNK", aliases: [] },
{ name: "Доминиканская Республика", code: "DOM", aliases: [] },
{ name: "Алжир", code: "DZA", aliases: [] },
{ name: "Эквадор", code: "ECU", aliases: [] },
{ name: "Египет", code: "EGY", aliases: [] },
{ name: "Эритрея", code: "ERI", aliases: [] },
{ name: "Западная Сахара", code: "ESH", aliases: [] },
{ name: "Испания", code: "ESP", aliases: [] },
{ name: "Эстония", code: "EST", aliases: [] },
{ name: "Эфиопия", code: "ETH", aliases: [] },
{ name: "Финляндия", code: "FIN", aliases: [] },
{ name: "Фиджи", code: "FJI", aliases: [] },
{ name: "Фолклендские острова", code: "FLK", aliases: [] },
{ name: "Франция", code: "FRA", aliases: [] },
{ name: "Фарерские острова", code: "FRO", aliases: [] },
{ name: "Микронезия", code: "FSM", aliases: [] },
{ name: "Габон", code: "GAB", aliases: [] },
{ name: "Великобритания", code: "GBR", aliases: ["Англия"] },
{ name: "Грузия", code: "GEO", aliases: [] },
{ name: "Гернси", code: "GGY", aliases: [] },
{ name: "Гана", code: "GHA", aliases: [] },
{ name: "Гибралтар", code: "GIB", aliases: [] },
{ name: "Гвинея", code: "GIN", aliases: [] },
{ name: "Гваделупа", code: "GLP", aliases: [] },
{ name: "Гамбия", code: "GMB", aliases: [] },
{ name: "Гвинея-Бисау", code: "GNB", aliases: [] },
{ name: "Экваториальная Гвинея", code: "GNQ", aliases: [] },
{ name: "Греция", code: "GRC", aliases: [] },
{ name: "Гренада", code: "GRD", aliases: [] },
{ name: "Гренландия", code: "GRL", aliases: [] },
{ name: "Гватемала", code: "GTM", aliases: [] },
{ name: "Гвиана", code: "GUF", aliases: [] },
{ name: "Гуам", code: "GUM", aliases: [] },
{ name: "Гайана", code: "GUY", aliases: [] },
{ name: "Гонконг", code: "HKG", aliases: [] },
{ name: "Остров Херд и острова Макдональд", code: "HMD", aliases: [] },
{ name: "Гондурас", code: "HND", aliases: [] },
{ name: "Хорватия", code: "HRV", aliases: [] },
{ name: "Гаити", code: "HTI", aliases: [] },
{ name: "Венгрия", code: "HUN", aliases: [] },
{ name: "Индонезия", code: "IDN", aliases: [] },
{ name: "Остров Мэн", code: "IMN", aliases: [] },
{ name: "Индия", code: "IND", aliases: [] },
{ name: "Британская территория в Индийском океане", code: "IOT", aliases: [] },
{ name: "Ирландия", code: "IRL", aliases: [] },
{ name: "Иран", code: "IRN", aliases: [] },
{ name: "Ирак", code: "IRQ", aliases: [] },
{ name: "Исландия", code: "ISL", aliases: [] },
{ name: "Израиль", code: "ISR", aliases: [] },
{ name: "Италия", code: "ITA", aliases: [] },
{ name: "Ямайка", code: "JAM", aliases: [] },
{ name: "Джерси", code: "JEY", aliases: [] },
{ name: "Иордания", code: "JOR", aliases: [] },
{ name: "Япония", code: "JPN", aliases: [] },
{ name: "Казахстан", code: "KAZ", aliases: [] },
{ name: "Кения", code: "KEN", aliases: [] },
{ name: "Киргизия", code: "KGZ", aliases: [] },
{ name: "Камбоджа", code: "KHM", aliases: [] },
{ name: "Кирибати", code: "KIR", aliases: [] },
{ name: "Сент-Китс и Невис", code: "KNA", aliases: [] },
{ name: "Южная Корея", code: "KOR", aliases: [] },
{ name: "Кувейт", code: "KWT", aliases: [] },
{ name: "Лаос", code: "LAO", aliases: [] },
{ name: "Ливан", code: "LBN", aliases: [] },
{ name: "Либерия", code: "LBR", aliases: [] },
{ name: "Ливия", code: "LBY", aliases: [] },
{ name: "Сент-Люсия", code: "LCA", aliases: [] },
{ name: "Лихтенштейн", code: "LIE", aliases: [] },
{ name: "Шри-Ланка", code: "LKA", aliases: [] },
{ name: "Лесото", code: "LSO", aliases: [] },
{ name: "Литва", code: "LTU", aliases: [] },
{ name: "Люксембург", code: "LUX", aliases: [] },
{ name: "Латвия", code: "LVA", aliases: [] },
{ name: "Макао", code: "MAC", aliases: [] },
{ name: "Сен-Мартен", code: "MAF", aliases: [] },
{ name: "Марокко", code: "MAR", aliases: [] },
{ name: "Монако", code: "MCO", aliases: [] },
{ name: "Молдавия", code: "MDA", aliases: [] },
{ name: "Мадагаскар", code: "MDG", aliases: [] },
{ name: "Мальдивы", code: "MDV", aliases: [] },
{ name: "Мексика", code: "MEX", aliases: [] },
{ name: "Маршалловы Острова", code: "MHL", aliases: [] },
{ name: "Северная Македония", code: "MKD", aliases: [] },
{ name: "Мали", code: "MLI", aliases: [] },
{ name: "Мальта", code: "MLT", aliases: [] },
{ name: "Мьянма", code: "MMR", aliases: [] },
{ name: "Черногория", code: "MNE", aliases: [] },
{ name: "Монголия", code: "MNG", aliases: [] },
{ name: "Северные Марианские острова", code: "MNP", aliases: [] },
{ name: "Мозамбик", code: "MOZ", aliases: [] },
{ name: "Мавритания", code: "MRT", aliases: [] },
{ name: "Монтсеррат", code: "MSR", aliases: [] },
{ name: "Мартиника", code: "MTQ", aliases: [] },
{ name: "Маврикий", code: "MUS", aliases: [] },
{ name: "Малави", code: "MWI", aliases: [] },
{ name: "Малайзия", code: "MYS", aliases: [] },
{ name: "Майотта", code: "MYT", aliases: [] },
{ name: "Намибия", code: "NAM", aliases: [] },
{ name: "Новая Каледония", code: "NCL", aliases: [] },
{ name: "Нигер", code: "NER", aliases: [] },
{ name: "Норфолк", code: "NFK", aliases: [] },
{ name: "Нигерия", code: "NGA", aliases: [] },
{ name: "Никарагуа", code: "NIC", aliases: [] },
{ name: "Ниуэ", code: "NIU", aliases: [] },
{ name: "Нидерланды", code: "NLD", aliases: [] },
{ name: "Норвегия", code: "NOR", aliases: [] },
{ name: "Непал", code: "NPL", aliases: [] },
{ name: "Науру", code: "NRU", aliases: [] },
{ name: "Новая Зеландия", code: "NZL", aliases: [] },
{ name: "Оман", code: "OMN", aliases: [] },
{ name: "Пакистан", code: "PAK", aliases: [] },
{ name: "Панама", code: "PAN", aliases: [] },
{ name: "Острова Питкэрн", code: "PCN", aliases: [] },
{ name: "Перу", code: "PER", aliases: [] },
{ name: "Филиппины", code: "PHL", aliases: [] },
{ name: "Палау", code: "PLW", aliases: [] },
{ name: "Папуа - Новая Гвинея", code: "PNG", aliases: [] },
{ name: "Польша", code: "POL", aliases: [] },
{ name: "Пуэрто-Рико", code: "PRI", aliases: [] },
{ name: "Северная Корея", code: "PRK", aliases: [] },
{ name: "Португалия", code: "PRT", aliases: [] },
{ name: "Парагвай", code: "PRY", aliases: [] },
{ name: "Палестина", code: "PSE", aliases: [] },
{ name: "Французская Полинезия", code: "PYF", aliases: [] },
{ name: "Катар", code: "QAT", aliases: [] },
{ name: "Реюньон", code: "REU", aliases: [] },
{ name: "Румыния", code: "ROU", aliases: [] },
{ name: "Россия", code: "RUS", aliases: [] },
{ name: "Руанда", code: "RWA", aliases: [] },
{ name: "Саудовская Аравия", code: "SAU", aliases: [] },
{ name: "Судан", code: "SDN", aliases: [] },
{ name: "Сенегал", code: "SEN", aliases: [] },
{ name: "Сингапур", code: "SGP", aliases: [] },
{ name: "Южная Георгия и Южные Сандвичевы Острова", code: "SGS", aliases: [] },
{ name: "Острова Святой Елены", code: "SHN", aliases: [] },
{ name: "Шпицберген и Ян-Майен", code: "SJM", aliases: [] },
{ name: "Соломоновы Острова", code: "SLB", aliases: [] },
{ name: "Сьерра-Леоне", code: "SLE", aliases: [] },
{ name: "Сальвадор", code: "SLV", aliases: [] },
{ name: "Сан-Марино", code: "SMR", aliases: [] },
{ name: "Сомали", code: "SOM", aliases: [] },
{ name: "Сен-Пьер и Микелон", code: "SPM", aliases: [] },
{ name: "Сербия", code: "SRB", aliases: [] },
{ name: "Южный Судан", code: "SSD", aliases: [] },
{ name: "Сан-Томе и Принсипи", code: "STP", aliases: [] },
{ name: "Суринам", code: "SUR", aliases: [] },
{ name: "Словакия", code: "SVK", aliases: [] },
{ name: "Словения", code: "SVN", aliases: [] },
{ name: "Швеция", code: "SWE", aliases: [] },
{ name: "Эсватини", code: "SWZ", aliases: [] },
{ name: "Синт-Мартен", code: "SXM", aliases: [] },
{ name: "Сейшельские Острова", code: "SYC", aliases: [] },
{ name: "Сирия", code: "SYR", aliases: [] },
{ name: "Тёркс и Кайкос", code: "TCA", aliases: [] },
{ name: "Чад", code: "TCD", aliases: [] },
{ name: "Того", code: "TGO", aliases: [] },
{ name: "Таиланд", code: "THA", aliases: [] },
{ name: "Таджикистан", code: "TJK", aliases: [] },
{ name: "Токелау", code: "TKL", aliases: [] },
{ name: "Туркменистан", code: "TKM", aliases: [] },
{ name: "Восточный Тимор", code: "TLS", aliases: [] },
{ name: "Тонга", code: "TON", aliases: [] },
{ name: "Тринидад и Тобаго", code: "TTO", aliases: [] },
{ name: "Тунис", code: "TUN", aliases: [] },
{ name: "Турция", code: "TUR", aliases: [] },
{ name: "Тувалу", code: "TUV", aliases: [] },
{ name: "Тайвань", code: "TWN", aliases: [] },
{ name: "Танзания", code: "TZA", aliases: [] },
{ name: "Уганда", code: "UGA", aliases: [] },
{ name: "Украина", code: "UKR", aliases: [] },
{ name: "Внешние малые острова США", code: "UMI", aliases: [] },
{ name: "Уругвай", code: "URY", aliases: [] },
{ name: "США", code: "USA", aliases: [] },
{ name: "Узбекистан", code: "UZB", aliases: [] },
{ name: "Ватикан", code: "VAT", aliases: [] },
{ name: "Сент-Винсент и Гренадины", code: "VCT", aliases: [] },
{ name: "Венесуэла", code: "VEN", aliases: [] },
{ name: "Виргинские Острова", code: "VGB", aliases: [] },
{ name: "Виргинские Острова", code: "VIR", aliases: [] },
{ name: "Вьетнам", code: "VNM", aliases: [] },
{ name: "Вануату", code: "VUT", aliases: [] },
{ name: "Уоллис и Футуна", code: "WLF", aliases: [] },
{ name: "Самоа", code: "WSM", aliases: [] },
{ name: "Йемен", code: "YEM", aliases: [] },
{ name: "ЮАР", code: "ZAF", aliases: [] },
{ name: "Замбия", code: "ZMB", aliases: [] },
{ name: "Зимбабве", code: "ZWE", aliases: [] },
{ name: "Абхазия", code: "ABH", aliases: [] },
        ],
        defaultValue: "",
        width: "280px",
    },
    
    
        {
        name: "Менеджер",
        code: "manager",
        type: "select",
        required: false,
        values: [
{ name: "Вася Пупкин", code: "vasyapupkin" },
{ name: "Иван Иванов", code: "ivan_ivanov" },
{ name: "Дед Пихто", code: "dedpikhto" },
        ],
        defaultValue: "",
        width: "160px",
        },
    
    
    
    
    {
        name: "ЧЗ",
        code: "trueMark",
        type: "checkbox",
        required: false,
        aliases: {
            yes: true,
            true: true,
            no: false,
            false: false,
        },
        defaultValue: false,
        width: "36px",
    },
];